name: grievancemanagement
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  provider: ^6.1.1
  shared_preferences: ^2.5.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/allassets/
  
  
